package com.growgenie.kidsyCore.model.screenState.screen.plan

/*
TODO: Make Plan content easier to access. It can not be just one line of json
TODO:
*/
class Plans {
    companion object {
        const val day0: String =
            "{\"id\":\"newborns_sleep_day1\",\"navigationBarTitle\":\"Newborn’s Sleep\",\"headline\":\"Day 1\",\"headlineBottom\":\"Understanding Newborn Sleep\",\"submit\":\"Begin\",\"screens\":[{\"type\":\"Prompt\",\"id\":\"welcome_screen\",\"headline\":\"Welcome to {kid_name}’s Sleep program, {user_name}!\",\"submitTop\":\"Tap anywhere to continue.\"},{\"type\":\"Question\",\"id\":\"track_sleep_question\",\"headline\":\"Do you track {kid_name} sleep?\",\"options\":[{\"id\":1,\"text\":\"Yes\"},{\"id\":2,\"text\":\"No\"},{\"id\":3,\"text\":\"Sometimes\"},{\"id\":4,\"text\":\"Don't know\"}],\"submit\":\"Continue\"},{\"type\":\"Prompt\",\"id\":\"tracking_sleep_info\",\"headline\":\"Tracking sleep patterns can help improve your baby's sleep quality.\",\"submitTop\":\"Tap anywhere to continue.\"},{\"type\":\"Prompt\",\"id\":\"tracking_naps_info\",\"headline\":\"Tracking naps ensures your baby gets enough rest throughout the day.\",\"submitTop\":\"Tap anywhere to continue.\"},{\"type\":\"Prompt\",\"id\":\"rested_babies_info\",\"headline\":\"It also makes your life easier. Well rested babies tend to be less nervous.\",\"submitTop\":\"Tap anywhere to continue.\"},{\"type\":\"Question\",\"id\":\"average_sleep_question\",\"headline\":\"On average, how much total sleep does {kid_name} get in a day?\",\"options\":[{\"id\":1,\"text\":\"12-16\"},{\"id\":2,\"text\":\"16-20\"},{\"id\":3,\"text\":\"20+\"},{\"id\":4,\"text\":\"Don't know\"}]},{\"type\":\"Prompt\",\"id\":\"newborn_sleep_info\",\"headline\":\"This is great! Newborns need 16-20 hours of sleep per day.\",\"submitTop\":\"Tap anywhere to continue.\"},{\"type\":\"Prompt\",\"id\":\"sleep_aids_info\",\"headline\":\"Sleep aids memory, senses, and exploration readiness.\",\"submitTop\":\"Tap anywhere to continue.\"},{\"type\":\"Prompt\",\"id\":\"track_nina_sleep\",\"headline\":\"For the next 5 days track Nina sleep as much as precise as you can.\",\"submitTop\":\"Tap anywhere to continue.\"},{\"type\":\"Prompt\",\"id\":\"uncover_routine_info\",\"headline\":\"It will uncover {kid_name} routine and help identify best patterns.\",\"submitTop\":\"Tap anywhere to continue.\"}]}"
    }
}